./longerline.out << EOF
one
three
longer
longest
eightyeightyeightyeightyeightyeightyeightyeighteightyeightyeightyeightyeightyeightyeightyeightyyeightyeightyeightyeightyeightyeightyeightyeighty
ninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninety
EOF

