./longer_than_eighty.out << EOF
one
three
longer
longest
eightyeightyeightyeightyeightyeightyeightyeighteightyeightyeightyeightyeightyeightyeightyeightyyeightyeightyeightyeightyeightyeightyeightyeighty
ninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninetyninety
EOF

